### ISSUE TITLE
[Feat] Add an option to turn it on/off

### ISSUE THREAD

**Issue by dmytro-shchurov** [fakt309/recosigns#1]
If this library is going to be used in a hybrid application (like Electron for SBC) or on a typical web site, browser handling of swiping will confuse user a lot imho.
What I see as an option, is to touch and hold waiting for some time until a recognition mode is turned on (with a custom timer and calling to the missed method). At the same moment scrolling can be disabled also.
This will allow to avoid false triggering while user scrolls.

UPD I wonder is .stopListen() lightweight enough to use it as on/off?

**Comment by fakt309** [comment]
dmytro-shchurov, thanks for feedback. It is very useful issue. I'll think about swiping and how to avoid collisions with third-party apps. What about .stopListen() this is pretty lightweight method. Since it only calls the function three times .removeEventListener(), to clear object events on "touchstart", "touchend", "touchmove". But if you want to turn on again, you need to  call .listen(DOMOBJECT)

**Comment by dmytro-shchurov** [comment]
Thank you very much for the explanations. I think this is what I meant.
I'd like to test your library in Electron application on Raspberry Pi (a music player) and let you know if any issues will be found. I believe it will be pretty useful there on 5" screen.
