### ISSUE TITLE
Question: Can this script work for the letters of the alphabet?

### ISSUE THREAD

**Issue by inglesuniversal** [fakt309/recosigns#3]
I would love to teach drawing the letters to kids in my classroom. 

Would it work for both capital and lowercase letters?

Best regards

**Comment by fakt309** [comment]
Hello. Thank you very much for your question. Unfortunately, there is no such possibility. Since this library is designed for a continuous drawing, so that the finger does not detach from the screen. But most letters of the alphabet require this. In the future, I will try to consider how this could be implemented. This is a very good idea.
